name             'artifactory-artifact'
maintainer       'Yamashita, Yuu'
maintainer_email 'yuu@treasure-data.com'
license          'Apache 2.0'
description      'Download artifacts from Artifactory'
long_description 'Download artifacts from Artifactory'
version          '0.6.0'
