name             'artifactory-artifact'
maintainer       'Yamashita, Yuu'
maintainer_email 'yuu@treasure-data.com'
license          'Apache 2.0'
description      'LWRP for artifacts on Artifactory'
long_description 'LWRP for artifacts on Artifactory'
version          '0.5.0'
